include:
  - package:flutter_lints/flutter.yaml
  - package:leancode_lint/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    # You can enable/disable specific rules here
    # For example:
    # - avoid_empty_blocks: true
    # - prefer_relative_imports: false
