name: test_lab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_ui_auth: ^1.16.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  provider: ^6.1.2
  google_sign_in: ^6.3.0
  internet_connection_checker_plus: ^2.7.1
  webview_flutter: ^4.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
