name: test_lab
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  app_settings: ^5.2.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_database: ^11.3.5
  firebase_ui_auth: ^1.16.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^19.0.0
  flutter_map: ^6.1.0
  google_sign_in: ^6.3.0
  gpx: ^2.3.0
  http: ^1.3.0
  internet_connection_checker_plus: ^2.7.1
  latlong2: ^0.9.0
  location: ^5.0.2+1
  mobile_scanner: ^6.0.0
  provider: ^6.1.2
  webview_flutter: ^4.10.0

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_dotenv: ^5.2.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  leancode_lint: ^15.1.0
  patrol: ^3.15.1

patrol:
  app_name: Test Lab
  android:
    package_name: io.github.zoskar.testlab
  ios:
    bundle_id: io.github.zoskar.testlab

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/locations.gpx
    - .patrol.env
